/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDevocionaisRouteImport } from './routes/_authenticated/devocionais'
import { Route as AuthenticatedBibliaIndexRouteImport } from './routes/_authenticated/biblia.index'
import { Route as AuthenticatedBibliaBookIdIndexRouteImport } from './routes/_authenticated/biblia.$bookId.index'
import { Route as AuthenticatedBibliaBookIdChapterRouteImport } from './routes/_authenticated/biblia.$bookId.$chapter'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDevocionaisRoute =
  AuthenticatedDevocionaisRouteImport.update({
    id: '/devocionais',
    path: '/devocionais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBibliaIndexRoute =
  AuthenticatedBibliaIndexRouteImport.update({
    id: '/biblia/',
    path: '/biblia/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBibliaBookIdIndexRoute =
  AuthenticatedBibliaBookIdIndexRouteImport.update({
    id: '/biblia/$bookId/',
    path: '/biblia/$bookId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBibliaBookIdChapterRoute =
  AuthenticatedBibliaBookIdChapterRouteImport.update({
    id: '/biblia/$bookId/$chapter',
    path: '/biblia/$bookId/$chapter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/devocionais': typeof AuthenticatedDevocionaisRoute
  '/biblia/': typeof AuthenticatedBibliaIndexRoute
  '/biblia/$bookId/$chapter': typeof AuthenticatedBibliaBookIdChapterRoute
  '/biblia/$bookId/': typeof AuthenticatedBibliaBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/devocionais': typeof AuthenticatedDevocionaisRoute
  '/biblia': typeof AuthenticatedBibliaIndexRoute
  '/biblia/$bookId/$chapter': typeof AuthenticatedBibliaBookIdChapterRoute
  '/biblia/$bookId': typeof AuthenticatedBibliaBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/devocionais': typeof AuthenticatedDevocionaisRoute
  '/_authenticated/biblia/': typeof AuthenticatedBibliaIndexRoute
  '/_authenticated/biblia/$bookId/$chapter': typeof AuthenticatedBibliaBookIdChapterRoute
  '/_authenticated/biblia/$bookId/': typeof AuthenticatedBibliaBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/devocionais'
    | '/biblia/'
    | '/biblia/$bookId/$chapter'
    | '/biblia/$bookId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/devocionais'
    | '/biblia'
    | '/biblia/$bookId/$chapter'
    | '/biblia/$bookId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/devocionais'
    | '/_authenticated/biblia/'
    | '/_authenticated/biblia/$bookId/$chapter'
    | '/_authenticated/biblia/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/devocionais': {
      id: '/_authenticated/devocionais'
      path: '/devocionais'
      fullPath: '/devocionais'
      preLoaderRoute: typeof AuthenticatedDevocionaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biblia/': {
      id: '/_authenticated/biblia/'
      path: '/biblia'
      fullPath: '/biblia/'
      preLoaderRoute: typeof AuthenticatedBibliaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biblia/$bookId/': {
      id: '/_authenticated/biblia/$bookId/'
      path: '/biblia/$bookId'
      fullPath: '/biblia/$bookId/'
      preLoaderRoute: typeof AuthenticatedBibliaBookIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biblia/$bookId/$chapter': {
      id: '/_authenticated/biblia/$bookId/$chapter'
      path: '/biblia/$bookId/$chapter'
      fullPath: '/biblia/$bookId/$chapter'
      preLoaderRoute: typeof AuthenticatedBibliaBookIdChapterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDevocionaisRoute: typeof AuthenticatedDevocionaisRoute
  AuthenticatedBibliaIndexRoute: typeof AuthenticatedBibliaIndexRoute
  AuthenticatedBibliaBookIdChapterRoute: typeof AuthenticatedBibliaBookIdChapterRoute
  AuthenticatedBibliaBookIdIndexRoute: typeof AuthenticatedBibliaBookIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDevocionaisRoute: AuthenticatedDevocionaisRoute,
  AuthenticatedBibliaIndexRoute: AuthenticatedBibliaIndexRoute,
  AuthenticatedBibliaBookIdChapterRoute: AuthenticatedBibliaBookIdChapterRoute,
  AuthenticatedBibliaBookIdIndexRoute: AuthenticatedBibliaBookIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
